---
- name: "Install and configure mariadb-server"
  hosts: all
  become: true
  vars_files:
    - mariadb.vars

  tasks:

    - name: "Mariadb - installation"
      yum:
       name:
         - mariadb-server
         - MySQL-python
       state: present

    - name: "Mariadb - Restart/Enable"
      service:
        name: mariadb
        state: restarted
        enabled: true

    - name: "Mariadb - setting root password"
      ignore_errors: yes
      mysql_user:
        login_user: "root"
        login_password: ""
        user: "root"
        password: "{{ mysql_root_password }}"
        host_all: yes

    - name: "Mariadb - removing anonymous user"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        user: ""
        host_all: yes
        state: absent

    - name: "Mariadb - removing test database"
      mysql_db:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        name: "test"
        state: absent

    - name: "Mariadb - adding database {{ wordpress_db }}"
      mysql_db:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        name: "{{ wordpress_db }}"
        state: present

    - name: "Mariadb - adding database user {{ wordpress_user }}"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        user: "{{ wordpress_user }}"
        host: localhost
        password: "{{ wordpress_password }}"
        priv: "{{ wordpress_db }}.*:ALL"
        state: present
